import type { TreeNode } from './types'

export const INIT: TreeNode[] = [
  {
    id: 'w1',
    text: 'Work',
    completed: false,
    collapsed: false,
    starred: false,
    children: [
      {
        id: 'w2',
        text: 'Q2 Marketing Launch',
        completed: false,
        collapsed: false,
        starred: false,
        children: [
          {
            id: 'w3',
            text: 'Draft email campaign',
            completed: true,
            collapsed: false,
            starred: false,
            children: [],
          },
          {
            id: 'w4',
            text: 'Design landing page',
            completed: false,
            collapsed: false,
            starred: true,
            children: [],
          },
          {
            id: 'w5',
            text: 'Set up A/B testing',
            completed: false,
            collapsed: false,
            starred: false,
            children: [],
          },
          {
            id: 'w6',
            text: 'Schedule social posts',
            completed: false,
            collapsed: false,
            starred: false,
            children: [],
          },
        ],
      },
      {
        id: 'w7',
        text: 'Team sync prep',
        completed: false,
        collapsed: false,
        starred: false,
        children: [
          {
            id: 'w8',
            text: 'Compile weekly metrics',
            completed: true,
            collapsed: false,
            starred: false,
            children: [],
          },
          {
            id: 'w9',
            text: 'Update roadmap slides',
            completed: false,
            collapsed: false,
            starred: true,
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: 'p1',
    text: 'Personal',
    completed: false,
    collapsed: false,
    starred: false,
    children: [
      {
        id: 'p2',
        text: 'Book dentist appointment',
        completed: false,
        collapsed: false,
        starred: true,
        children: [],
      },
      {
        id: 'p3',
        text: 'Renew gym membership',
        completed: false,
        collapsed: false,
        starred: false,
        children: [],
      },
      {
        id: 'p4',
        text: 'Weekend trip planning',
        completed: false,
        collapsed: false,
        starred: false,
        children: [
          {
            id: 'p5',
            text: 'Check hotel prices',
            completed: true,
            collapsed: false,
            starred: false,
            children: [],
          },
          {
            id: 'p6',
            text: 'Book train tickets',
            completed: false,
            collapsed: false,
            starred: false,
            children: [],
          },
          {
            id: 'p7',
            text: 'Pack bag',
            completed: false,
            collapsed: false,
            starred: false,
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: 'i1',
    text: 'Ideas',
    completed: false,
    collapsed: false,
    starred: false,
    children: [
      {
        id: 'i2',
        text: 'Build a To-Do Tree app',
        completed: false,
        collapsed: false,
        starred: true,
        children: [],
      },
      {
        id: 'i3',
        text: 'Write a short story',
        completed: false,
        collapsed: false,
        starred: false,
        children: [],
      },
    ],
  },
]
